-- WorkSafe AI
-- Create base tables

CREATE OR REPLACE TABLE RAW_WORK_DATA (
  ORG_NAME STRING,
  INDUSTRY STRING,
  DEPARTMENT STRING,
  RAW_PAYLOAD VARIANT,
  INGESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE INDUSTRY_RULES (
  INDUSTRY STRING,
  MAX_SHIFT_HOURS NUMBER,
  MIN_REST_HOURS NUMBER
);

-- Sample rules (can be customized per org / policy)
INSERT INTO INDUSTRY_RULES VALUES
('Healthcare', 12, 8),
('IT', 10, 10);
