-- WorkSafe AI
-- Normalize raw workforce data

CREATE OR REPLACE VIEW NORMALIZED_SHIFTS AS
SELECT
  ORG_NAME,
  INDUSTRY,
  DEPARTMENT,
  RAW_PAYLOAD:"staff_id"::STRING AS STAFF_ID,
  RAW_PAYLOAD:"role"::STRING AS ROLE,
  TO_TIMESTAMP(RAW_PAYLOAD:"shift_start"::STRING) AS SHIFT_START,
  TO_TIMESTAMP(RAW_PAYLOAD:"shift_end"::STRING) AS SHIFT_END
FROM RAW_WORK_DATA;
