-- WorkSafe AI
-- Calculate metrics and detect unsafe patterns

-- Step 1: Compute shift duration and rest gap
CREATE OR REPLACE VIEW SHIFT_METRICS AS
SELECT
  n.ORG_NAME,
  n.INDUSTRY,
  n.DEPARTMENT,
  n.STAFF_ID,
  n.ROLE,
  n.SHIFT_START,
  n.SHIFT_END,
  DATEDIFF('hour', SHIFT_START, SHIFT_END) AS SHIFT_HOURS,
  DATEDIFF(
    'hour',
    LAG(SHIFT_END) OVER (
      PARTITION BY STAFF_ID
      ORDER BY SHIFT_START
    ),
    SHIFT_START
  ) AS REST_HOURS
FROM NORMALIZED_SHIFTS n;

-- Step 2: Flag unsafe patterns using industry rules
CREATE OR REPLACE VIEW UNSAFE_PATTERNS AS
SELECT
  m.INDUSTRY,
  m.DEPARTMENT,
  m.STAFF_ID,
  CASE
    WHEN m.SHIFT_HOURS > r.MAX_SHIFT_HOURS THEN 'LONG_SHIFT'
    WHEN m.REST_HOURS IS NOT NULL AND m.REST_HOURS < r.MIN_REST_HOURS THEN 'INSUFFICIENT_REST'
    ELSE 'SAFE'
  END AS RISK_FLAG
FROM SHIFT_METRICS m
JOIN INDUSTRY_RULES r
  ON m.INDUSTRY = r.INDUSTRY
WHERE
  m.SHIFT_HOURS > r.MAX_SHIFT_HOURS
  OR (m.REST_HOURS IS NOT NULL AND m.REST_HOURS < r.MIN_REST_HOURS);
